language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
addons:
  apt:
    packages:
      - libsecret-1-dev
install: npm install
jobs:
  include:
    - stage: test
      script:
        - npm run compile:prod
        - npm run lint
        - npm run test
    - stage: deploy
      if: branch = master
      script: npm run semantic-release
